spring.application.name=ride-gateway

server.port=8080

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.mvc.routes[0].id=auth-service
spring.cloud.gateway.mvc.routes[0].uri=lb://ride-auth
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.mvc.routes[1].id=ride-service
spring.cloud.gateway.mvc.routes[1].uri=lb://ride-service
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/v1/rides/**

spring.cloud.gateway.mvc.routes[2].id=payment-service
spring.cloud.gateway.mvc.routes[2].uri=lb://ride-payment
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/v1/payments/**

# Logging
logging.level.com.ridebooking.gateway=DEBUG
