spring.application.name=ride-ride

server.port=8082

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ride_ride_db?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Sula@991215}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Other Service URLs
gateway.service.url=http://localhost:8080
auth.service.url=http://localhost:8081
payment.service.url=http://localhost:8083
notification.service.url=http://localhost:8084

# Logging
logging.level.com.ridebooking.ride=DEBUG
